---
- name: OpenVPN | Update apt cache
  apt:
    update_cache: yes
  become: yes
  changed_when: false

- name: OpenVPN | Install OpenVPN and Easy-RSA
  apt:
    name: "{{ openvpn_packages }}"
    state: present
  become: yes

- name: OpenVPN | Ensure Easy-RSA directory exists
  block:
    - name: OpenVPN | Check if Easy-RSA directory exists
      stat:
        path: "{{ easy_rsa_path }}"
      register: easy_rsa_exists

    - name: OpenVPN | Create Easy-RSA directory if it doesn't exist
      command: make-cadir "{{ easy_rsa_path }}"
      become: yes
      when: not easy_rsa_exists.stat.exists

- name: OpenVPN | Ensure PKI directory exists
  block:
    - name: OpenVPN | Check if PKI directory exists
      stat:
        path: "{{ easy_rsa_pki_path }}"
      register: pki_exists

    - name: OpenVPN | Create PKI directory if it doesn't exist
      command: ./easyrsa init-pki
      args:
        chdir: "{{ easy_rsa_path }}"
      become: yes
      when: not pki_exists.stat.exists

- name: OpenVPN | Create and manage CA and server certificates
  block:
    - name: OpenVPN | Check if CA certificate already exists
      stat:
        path: "{{ easy_rsa_pki_path }}/ca.crt"
      register: ca_cert

    - name: OpenVPN | Build CA without password and common name
      shell: echo "MyOpenVPN_CA" | ./easyrsa build-ca nopass
      args:
        chdir: "{{ easy_rsa_path }}"
      become: yes
      when: not ca_cert.stat.exists

    - name: OpenVPN | Check if server key already exists
      stat:
        path: "{{ easy_rsa_pki_path }}/private/server.key"
      register: server_key

    - name: OpenVPN | Generate server request without password
      shell: echo "MyOpenVPN_Server" | ./easyrsa gen-req server nopass
      args:
        chdir: "{{ easy_rsa_path }}"
      become: yes
      when: not server_key.stat.exists

    - name: OpenVPN | Check if server certificate already exists
      stat:
        path: "{{ easy_rsa_pki_path }}/issued/server.crt"
      register: server_cert

    - name: OpenVPN | Request sign for server certificate
      shell: echo "yes" | ./easyrsa sign-req server server
      args:
        chdir: "{{ easy_rsa_path }}"
      become: yes
      when: not server_cert.stat.exists

    - name: OpenVPN | Check if Diffie-Hellman parameters already exist
      stat:
        path: "{{ easy_rsa_pki_path }}/dh.pem"
      register: dh_params

    - name: OpenVPN | Generate Diffie-Hellman parameters
      command: ./easyrsa gen-dh
      args:
        chdir: "{{ easy_rsa_path }}"
      become: yes
      when: not dh_params.stat.exists

    - name: OpenVPN | Check if TLS key already exists
      stat:
        path: "{{ easy_rsa_pki_path }}/ta.key"
      register: tls_key

    - name: OpenVPN | Generate TLS key
      command: openvpn --genkey --secret pki/ta.key
      args:
        chdir: "{{ easy_rsa_path }}"
      become: yes
      when: not tls_key.stat.exists

- name: OpenVPN | Ensure OpenVPN directory
  file:
    path: /etc/openvpn
    state: directory
    mode: '0755'
  become: yes

- name: OpenVPN | Copy required files to OpenVPN directory
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    force: no
  with_items:
    - { src: "{{ easy_rsa_pki_path }}/ca.crt", dest: "{{ openvpn_config_path }}/ca.crt" }
    - { src: "{{ easy_rsa_pki_path }}/issued/server.crt", dest: "{{ openvpn_config_path }}/server.crt" }
    - { src: "{{ easy_rsa_pki_path }}/private/server.key", dest: "{{ openvpn_config_path }}/server.key" }
    - { src: "{{ easy_rsa_pki_path }}/dh.pem", dest: "{{ openvpn_config_path }}/dh.pem" }
    - { src: "{{ easy_rsa_pki_path }}/ta.key", dest: "{{ openvpn_config_path }}/ta.key" }
  become: yes

- name: OpenVPN | Apply OpenVPN server configuration
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
  become: yes

- name: OpenVPN | Check if OpenVPN is running
  shell: pgrep -f "openvpn --config /etc/openvpn/server.conf"
  register: openvpn_process
  ignore_errors: true
  changed_when: false

- name: OpenVPN | Start OpenVPN server manually
  command: openvpn --config /etc/openvpn/server.conf
  async: 30
  poll: 0
  become: yes
  when: openvpn_process.rc != 0

- name: OpenVPN | Create destination directory on remote machine
  file:
    path: "{{ artifacts_path }}"
    state: directory
    mode: '0755'

- name: OpenVPN | Create destination directory on local machine
  local_action:
    module: file
    path: "./artifacts"
    owner: sashasteingart
    state: directory
    mode: '0755'



- name: OpenVPN | Create client configuration file
  template:
    src: client.ovpn.j2
    dest: "{{ artifacts_path }}/client.ovpn"

- name: OpenVPN | Fetch client.ovpn file to local machine
  fetch:
    src: "{{ artifacts_path }}/client.ovpn"
    dest: "./artifacts/client.ovpn"
    flat: yes
